#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes {
    DELWORD = SAFE_RANGE,
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
    case DELWORD:
        if (record->event.pressed) {
            register_code(KC_LCTL);
            register_code(KC_BSPC);
        } else {
            unregister_code(KC_BSPC);
            unregister_code(KC_LCTL);
        }
        break;
    }
    return true;
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
        // [0] = LAYOUT_split_3x6_5(
        //   KC_TAB, KC_Q, KC_W, KC_F, KC_P, KC_G,                                       KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_QUOT,
        //   KC_BSPC, KC_A, KC_R, KC_S, KC_T, KC_D,                                      KC_H, KC_N, KC_E, KC_I, KC_O, KC_ENT,
        //   KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LBRC, KC_ESC,     MO(3), KC_RBRC, KC_K, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT,
        //                 MO(4), KC_LGUI, KC_LCTL, QK_LEAD, MO(1),      MO(2), KC_SPC, KC_RALT, KC_CAPS, KC_APP
        // ),
        [0] = LAYOUT_split_3x6_5(
          KC_TAB, KC_Q, KC_W, KC_F, KC_P, KC_G,                                       KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_QUOT,
          KC_BSPC, LGUI_T(KC_A), LALT_T(KC_R), LSFT_T(KC_S), LCTL_T(KC_T), KC_D,      KC_H, LCTL_T(KC_N), LSFT_T(KC_E), LALT_T(KC_I), LGUI_T(KC_O), KC_ENT,
          KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LBRC, KC_ESC,                     MO(3), KC_RBRC, KC_K, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT,
                        MO(4), KC_LGUI, KC_LCTL, DELWORD, MO(1),                      MO(2), KC_SPC, KC_RALT, KC_CAPS, KC_APP
        ),
        [1] = LAYOUT_split_3x6_5(
          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                                         KC_PGUP, KC_HOME, KC_UP, KC_END, KC_VOLU, KC_DEL,
          KC_TRNS, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_TRNS,                                         KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_VOLD, KC_INS,
          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_SCRL,     KC_TRNS, KC_TRNS, KC_PAUS, KC_MPRV, KC_MPLY, KC_MNXT, KC_MUTE, KC_PSCR,
                                    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
        ),
        [2] = LAYOUT_split_3x6_5(
          KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5,                                                         KC_6, KC_7, KC_8, KC_9, KC_0, KC_EQL,
          KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC,                                            KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_PLUS,
          KC_PIPE, KC_BSLS, KC_COLN, KC_SCLN, KC_MINS, KC_LBRC, KC_LCBR, KC_TRNS,     KC_TRNS, KC_RCBR, KC_RBRC, KC_UNDS, KC_COMM, KC_DOT, KC_SLSH, KC_QUES,
                                    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
        ),
        [3] = LAYOUT_split_3x6_5(
          KC_TRNS, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS,                                          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
          KC_TRNS, KC_F5, KC_F6, KC_F7, KC_F8, KC_TRNS,                                             KC_TRNS, KC_RSFT, KC_RCTL, KC_LALT, KC_RGUI, KC_TRNS,
          KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_TRNS, KC_TRNS, KC_TRNS,         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                                KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
        ),
        [4] = LAYOUT_split_3x6_5(
          KC_TRNS, KC_TRNS, KC_TRNS, DF(0), KC_TRNS, KC_TRNS,                                         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
          KC_TRNS, KC_TRNS, KC_TRNS, DF(1), KC_TRNS, KC_TRNS,                                         RGB_TOG, RGB_SAI, RGB_HUI, RGB_VAI, RGB_MOD, KC_TRNS,
          KC_TRNS, KC_TRNS, KC_TRNS, DF(2), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_TRNS, KC_TRNS, KC_TRNS, RGB_SAD, RGB_HUD, RGB_VAD, RGB_RMOD, KC_TRNS,
                                    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
        )
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};

#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

void keyboard_pre_init_user(void) {
  // Set our LED pin as output
  setPinOutput(24);
  // Turn the LED off
  // (Due to technical reasons, high is off and low is on)
  writePinHigh(24);
}

void leader_end_user(void) {
  if (leader_sequence_one_key(KC_G)) { // Greeting
    SEND_STRING("Mit freundlichen Gr");
    SEND_STRING(SS_RALT("u") SS_RALT("s"));
    SEND_STRING("en\n\nJonas Wotzlawski");
  }
}
